events {}

http{
    server{
        listen 80;

        location /products/ {
            proxy_pass http://products:8000/products;
        }
        location /orders/ {
            proxy_pass http://orders:8000/orders;
        }
        location /products-docs {
            proxy_pass http://products:8000/docs;
        }
        location /orders-docs {
            proxy_pass http://orders:8000/docs;
        }
    }
}